name: CI and CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      - name: Set-up Node
        uses: actions/setup-node@v3
        with:
          node-version:  "10.x"
      - run: npm install
      - run: npm run build
      - run: npm test
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: main
          build_dir: public  
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}